### ISSUE TITLE
sbt-thrift doesn't support language options

### ISSUE THREAD

**Issue by sritchie** [twitter/sbt-thrift#10]
By default, thrift doesn't generate hashcodes for its structs; this must be supplied as an option to thrift-finagle, like

`--gen java:hashcode`

I'm not sure how to do it, but I think adding an "options" val right around here will do the trick:

https://github.com/twitter/sbt-thrift/blob/master/src/main/scala/com/twitter/sbt/CompileThrift.scala#L96

**Comment by grimreaper** [comment]
Thank you for your contribution! Twitter has decided to stop supporting FlockDB as an open source project. Sorry that your pull requests was not reviewed earlier.
We're now formally archiving this project but please feel free to fork and resurrect.
